name: timechart
version: 'v0.0.1'
summary: Time tracking app to show you what you spend your time on
description: |
  Time tracking app to show you what you spend your time on

grade: devel
confinement: devmode

base: core18

parts:
  timechart:
    plugin: dump
    source: dist/timechart
    source-type: local
    stage-packages:
      - libgl1

apps:
  timechart:
    command: timechart
    plugs: [desktop, x11, wayland, opengl, dbus]
    desktop: share/application/timechart.desktop
    passthrough:
      autostart: timechart-autostart.desktop
